config/routes.rb
Autizen::Application.routes.draw do

  resources :triggers

  root :to => 'main#controls', :as => :controls

  post 'create' => 'triggers#create', :as => :create_trigger

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def controls
		@triggers = Trigger.all
	end

	helper_method :find_icon

	def find_icon(command)
		if command == "the humidity is higher than xx%" or command == "the humidity is lower than xx%" or command == "turn on the humidifier"
			return "humidifier.png"
		end
		if command == "turn on the air filter"
			return "air_filter.png"
		end
		if command == "motion is detected"
			return "motion.png"
		end
		if command == "turn on the light" or command == "turn off the light"
			return "light.png"
		end
	end

end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController

	def new
			
	end

	def create
		add = Trigger.new

		add.trigger = params[:trigger]
		add.action = params[:reaction]
		add.save

		redirect_to controls_url
	end

	def destroy
    @trigger = Trigger.find params[:id]
    @trigger.destroy
    redirect_to controls_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zense</title>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:400,700|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="core wrapper">
	<header>
		<div class="mobile-nav menu-icon">
			<%= image_tag "menu-icon.png" %>
		</div>
		<div class="logo">
			<%= link_to controls_url do %>
				<%= image_tag("zense.png") %>
			<% end %>
		</div>
		<nav>
 			<ul class="mobile">
        <li><%= link_to "Your Controls", controls_url %></li>
 				<li><a href="events.php">Sensory Sensitivity Quiz</a></li>
 				<li><a href="news.php">More Information</a></li>
 			</ul>
 		</nav>
	</header>

	<div class="content">
		<%= yield %>
	</div>

	<div class="push">
	</div>
</div>
<footer>
</footer>


<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/main/controls.html.erb
<h1>your controls</h1>

<% @triggers.each do |trigger| %>
	<div class="trigger">
		<div class="title">
			<p>When <em><%= trigger.trigger %></em> please <em><%= trigger.action %></em></p>
			<%= link_to trigger_url(trigger), method: 'delete' do %>
				<div class="x">&times;</div>
			<% end %>
		</div>
		<div class="trigger-img"><%= image_tag(find_icon(trigger.trigger)) %></div>
		<div class="arrow-area"><div class="arrow"><%= image_tag("arrow.png") %></div></div>
		<div class="action-img"><%= image_tag(find_icon(trigger.action)) %></div>
	</div>
<% end %>

<%= link_to new_trigger_url do %>
	<div class="trigger last">
		<div class="add">&plus;</div>
	</div>
<% end %>

app/views/triggers/new.html.erb
<h1>new trigger</h1>

<%= form_tag create_trigger_url, method: "post", class: "new-trigger" do %>
	<h2>when</h2>
	<div class="styled-select slate">
		<%= select_tag "trigger", options_for_select([ "the humidity is higher than xx%", "the humidity is lower than xx%", "motion is detected" ], "humidity is higher than 30%")%>
	</div>
	<h2>please</h2>
	<div class="styled-select slate">
		<%= select_tag "reaction", options_for_select([ "turn on the humidifier", "turn off the humidifier", "turn on the light", "turn off the light" ], "turn on the humidifier")%>
	</div>
	<%= submit_tag "create control" %>
<% end %>